# Devtools 

devtools::use_code_of_conduct()
devtools::use_cran_badge()
devtools::use_mit_license()
devtools::use_news_md()
devtools::use_readme_rmd()
devtools::use_testthat()
devtools::use_test("init")
devtools::use_vignette("getting started")
devtools::use_package("tidytext")
devtools::use_package("dplyr")
devtools::use_package("magrittr")
devtools::use_package("stringr")
devtools::use_package("purrr")
devtools::use_package("rlang")
devtools::build_vignettes()
